(function(){
'use strict';
function $(id){return document.getElementById(id)}
var file=$('file'),fileName=$('fileName'),steps=$('steps'),bpm=$('bpm'),mechanism=$('mechanism'),sensitivity=$('sensitivity');
var generate=$('generate'),test=$('test'),listen=$('listen'),audio=$('audio'),download=$('download');
var status=$('status'),canvas=$('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});
var empty=$('empty'),scan=$('scan'),previewCard=$('previewCard'),analysisLabel=$('analysisLabel'),palette=$('palette'),dropZone=$('dropZone');
var source=null,events=[],audioUrl='',songMeta=null,lastKey=-1,scanFrame=0,paletteClusters=[],paper=null;
var ROOT_NAMES=['C','D♭','D','E♭','E','F','F♯','G','A♭','A','B♭','B'];
var MAJOR=[0,2,4,5,7,9,11],MINOR=[0,2,3,5,7,8,10];
function setStatus(text){status.textContent=text}
function clamp(x,a,b){return Math.min(b,Math.max(a,x))}
function hz(midi){return 440*Math.pow(2,(midi-69)/12)}
function rgbToHsv(r,g,b){r/=255;g/=255;b/=255;var max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min,h=0;if(d!==0){if(max===r)h=60*(((g-b)/d)%6);else if(max===g)h=60*((b-r)/d+2);else h=60*((r-g)/d+4)}if(h<0)h+=360;return{h:h,s:max===0?0:d/max,v:max}}
function srgbLinear(v){v/=255;return v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4)}
function rgbToLab(r,g,b){var R=srgbLinear(r),G=srgbLinear(g),B=srgbLinear(b);var x=(R*.4124564+G*.3575761+B*.1804375)/.95047,y=(R*.2126729+G*.7151522+B*.072175),z=(R*.0193339+G*.119192+B*.9503041)/1.08883;function f(t){return t>.008856?Math.pow(t,1/3):7.787*t+16/116}var fx=f(x),fy=f(y),fz=f(z);return{l:116*fy-16,a:500*(fx-fy),b:200*(fy-fz)}}
function labDistance(a,b){var dl=(a.l-b.l)*.45,da=a.a-b.a,db=a.b-b.b;return Math.sqrt(dl*dl+da*da+db*db)}
function chromaDistance(a,b){var da=a.a-b.a,db=a.b-b.b;return Math.sqrt(da*da+db*db)}
function median(arr){if(!arr.length)return 0;arr.sort(function(a,b){return a-b});var m=Math.floor(arr.length/2);return arr.length%2?arr[m]:(arr[m-1]+arr[m])/2}
function colorName(rgb){var hsv=rgbToHsv(rgb.r,rgb.g,rgb.b);if(hsv.s<.16)return hsv.v<.42?'灰':'淡色';var h=hsv.h;if(h<15||h>=345)return'赤';if(h<38)return'橙';if(h<66)return'黄';if(h<95)return'黄緑';if(h<155)return'緑';if(h<190)return'青緑';if(h<220)return'水色';if(h<255)return'青';if(h<285)return'紫';if(h<325)return'藤・桃';return'紅'}
function toHex(v){var s=clamp(Math.round(v),0,255).toString(16);return s.length<2?'0'+s:s}
function updatePalette(clusters){palette.innerHTML='';paletteClusters=clusters.slice(0,6);for(var i=0;i<paletteClusters.length;i++){var c=paletteClusters[i],sw=document.createElement('span'),hex='#'+toHex(c.r)+toHex(c.g)+toHex(c.b);sw.style.background=hex;sw.title=colorName(c)+' '+hex.toUpperCase();sw.setAttribute('aria-label',sw.title);palette.appendChild(sw)}palette.classList.toggle('visible',paletteClusters.length>0)}
function random01(){if(window.crypto&&window.crypto.getRandomValues){var a=new Uint32Array(1);window.crypto.getRandomValues(a);return a[0]/4294967296}return Math.random()}
function seeded(seed){var x=seed|0;return function(){x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function ascii(view,offset,text){for(var i=0;i<text.length;i++)view.setUint8(offset+i,text.charCodeAt(i))}
function wavStereo(left,right,sr){var length=Math.min(left.length,right.length),buffer=new ArrayBuffer(44+length*4),view=new DataView(buffer);ascii(view,0,'RIFF');view.setUint32(4,36+length*4,true);ascii(view,8,'WAVE');ascii(view,12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,2,true);view.setUint32(24,sr,true);view.setUint32(28,sr*4,true);view.setUint16(32,4,true);view.setUint16(34,16,true);ascii(view,36,'data');view.setUint32(40,length*4,true);for(var i=0;i<length;i++){var l=clamp(left[i],-1,1),r=clamp(right[i],-1,1),o=44+i*4;view.setInt16(o,l<0?l*32768:l*32767,true);view.setInt16(o+2,r<0?r*32768:r*32767,true)}return new Blob([buffer],{type:'audio/wav'})}
function mixSample(left,right,index,value,pan){if(index<0||index>=left.length)return;var angle=(clamp(pan,-1,1)+1)*Math.PI/4;left[index]+=value*Math.cos(angle);right[index]+=value*Math.sin(angle)}
function addMusicBox(left,right,sr,start,midi,volume,pan,seed,duration){var begin=Math.floor(start*sr),end=Math.min(left.length,begin+Math.floor(duration*sr)),f=hz(midi),rnd=seeded(seed);var partials=[1,2.008,2.97,4.075,5.42,6.76],amps=[1,.48,.24,.12,.068,.036],decays=[1.12,.72,.48,.34,.25,.2],phases=[];for(var p=0;p<partials.length;p++)phases.push(rnd()*Math.PI*2);for(var i=begin;i<end;i++){var t=(i-begin)/sr,attack=Math.min(1,t/.0018),body=Math.exp(-t/1.05)+.18*Math.exp(-t/2.6),s=0;var flutter=.012*Math.sin(2*Math.PI*5.1*t+phases[0])+.005*Math.sin(2*Math.PI*8.7*t+phases[1]);for(var j=0;j<partials.length;j++)s+=Math.sin(2*Math.PI*f*partials[j]*t+phases[j]+flutter*partials[j])*amps[j]*Math.exp(-t/decays[j]);s+=.11*Math.sin(2*Math.PI*(f*.503)*t+phases[2])*Math.exp(-t/.42);if(t<.016)s+=(rnd()*2-1)*(.12*(1-t/.016));mixSample(left,right,i,s*attack*body*volume*.19,pan)}}
function addClick(left,right,sr,start,volume,pan,seed){var begin=Math.floor(start*sr),end=Math.min(left.length,begin+Math.floor(.04*sr)),rnd=seeded(seed);for(var i=begin;i<end;i++){var t=(i-begin)/sr,e=Math.exp(-t/.006),noise=(rnd()*2-1)*.55,tone=Math.sin(2*Math.PI*1850*t)*.45;mixSample(left,right,i,(noise+tone)*e*volume,pan)}}
function addWindUp(left,right,sr,amount,seed){if(amount<=0)return;var rnd=seeded(seed),t=.08;while(t<1.34){addClick(left,right,sr,t,.045+amount*.11,-.28+rnd()*.55,seed+Math.floor(t*10000));t+=.105-rnd()*.035}var end=Math.min(left.length,Math.floor(1.5*sr));for(var i=0;i<end;i++){var x=i/sr,e=Math.sin(Math.PI*clamp(x/1.48,0,1)),whirr=Math.sin(2*Math.PI*(74+38*x)*x)*.018+(rnd()*2-1)*.008;mixSample(left,right,i,whirr*e*amount,0)}}
function addMechanismBed(left,right,sr,start,end,stepSec,amount,seed){if(amount<=0)return;var rnd=seeded(seed),t=start;while(t<end){addClick(left,right,sr,t,.012+amount*.035,-.35+rnd()*.7,seed+Math.floor(t*1000));t+=stepSec*(.98+(rnd()-.5)*.035)}var a=Math.floor(start*sr),z=Math.min(left.length,Math.floor(end*sr));for(var i=a;i<z;i++){var x=(i-a)/sr,slow=.0045*Math.sin(2*Math.PI*2.15*x)+(rnd()*2-1)*.0017;mixSample(left,right,i,slow*amount,0)}}
function normalize(left,right){var peak=.0001,i;for(i=0;i<left.length;i++)peak=Math.max(peak,Math.abs(left[i]),Math.abs(right[i]));var gain=Math.min(1.8,.91/peak);for(i=0;i<left.length;i++){left[i]=Math.tanh(left[i]*gain);right[i]=Math.tanh(right[i]*gain)}}
function chooseKey(){var pc=Math.floor(random01()*12);if(pc===lastKey)pc=(pc+1+Math.floor(random01()*11))%12;lastKey=pc;var minor=random01()<.4,intervals=minor?MINOR:MAJOR,base=60+pc;while(base<64)base+=12;while(base>71)base-=12;var notes=[];for(var oct=0;oct<3;oct++)for(var i=0;i<intervals.length;i++)notes.push(base+intervals[i]+oct*12);return{pc:pc,minor:minor,intervals:intervals,base:base,notes:notes,name:ROOT_NAMES[pc]+(minor?' minor':' major'),jp:ROOT_NAMES[pc]+(minor?'短調':'長調')}}
function useBlob(blob,name,meta){if(audioUrl)URL.revokeObjectURL(audioUrl);audioUrl=URL.createObjectURL(blob);songMeta=meta||null;audio.pause();audio.src=audioUrl;audio.load();download.href=audioUrl;download.download=name;download.hidden=false;listen.disabled=false;setStatus('音声ができました。黒い「できた曲を再生」を押してください。')}
function makeTest(){setStatus('オルゴールの音色を作っています…');var sr=32000,duration=7,left=new Float32Array(sr*duration),right=new Float32Array(sr*duration),amount=Number(mechanism.value)/100;addWindUp(left,right,sr,amount,1097);var notes=[72,76,79,84,79,76,72];for(var i=0;i<notes.length;i++)addMusicBox(left,right,sr,1.45+i*.58,notes[i],.88,(i/(notes.length-1)-.5)*.45,400+i,3.1);addMechanismBed(left,right,sr,1.43,6.1,.58,amount,714);normalize(left,right);$('keyName').textContent='C長調・音色サンプル';useBlob(wavStereo(left,right,sr),'musicbox-sound-test.wav',{intro:1.45,length:4.2})}
function estimatePaper(){var w=source.width,h=source.height,d=source.data,stride=Math.max(2,Math.floor(Math.min(w,h)/180)),samples=[];for(var y=0;y<h;y+=stride){for(var x=0;x<w;x+=stride){var edge=x<w*.14||x>w*.86||y<h*.14||y>h*.86,k=(y*w+x)*4,r=d[k],g=d[k+1],b=d[k+2],lab=rgbToLab(r,g,b),hsv=rgbToHsv(r,g,b),c=Math.sqrt(lab.a*lab.a+lab.b*lab.b);if((edge||lab.l>82)&&lab.l>54&&c<42&&hsv.v>.5)samples.push({r:r,g:g,b:b,l:lab.l,a:lab.a,bb:lab.b})}}if(!samples.length)return{r:245,g:242,b:234,lab:rgbToLab(245,242,234)};samples.sort(function(a,b){return b.l-a.l});samples=samples.slice(0,Math.max(20,Math.floor(samples.length*.5)));var rs=[],gs=[],bs=[],ls=[],as=[],bbs=[];for(var i=0;i<samples.length;i++){rs.push(samples[i].r);gs.push(samples[i].g);bs.push(samples[i].b);ls.push(samples[i].l);as.push(samples[i].a);bbs.push(samples[i].bb)}return{r:median(rs),g:median(gs),b:median(bs),lab:{l:median(ls),a:median(as),b:median(bbs)}}}
function classifyPixel(r,g,b,sens){var lab=rgbToLab(r,g,b),hsv=rgbToHsv(r,g,b),cd=chromaDistance(lab,paper.lab),dark=paper.lab.l-lab.l,chroma=Math.sqrt(lab.a*lab.a+lab.b*lab.b);var colorThreshold=19-sens*7.5,satThreshold=.21-sens*.075,chromaThreshold=19-sens*6;var color=cd>colorThreshold&&chroma>chromaThreshold&&hsv.s>satThreshold&&lab.l>13&&hsv.v>.12;var red=color&&(hsv.h<27||hsv.h>337)&&r>g*1.1&&r>b*1.08;var ink=!color&&dark>(17-sens*3)&&lab.l<78;return{lab:lab,hsv:hsv,color:color,red:red,ink:ink,cd:cd,dark:dark}}
function buildPalette(samples){if(!samples.length)return[];var centers=[],first=samples[0];for(var i=1;i<samples.length;i++)if(samples[i].w>first.w)first=samples[i];centers.push({l:first.lab.l,a:first.lab.a,b:first.lab.b,r:first.r,g:first.g,bb:first.b});while(centers.length<6){var best=null,bestD=0;for(i=0;i<samples.length;i++){var md=1e9;for(var j=0;j<centers.length;j++)md=Math.min(md,labDistance(samples[i].lab,centers[j]));var score=md*Math.sqrt(samples[i].w);if(score>bestD){bestD=score;best=samples[i]}}if(!best||bestD<16)break;centers.push({l:best.lab.l,a:best.lab.a,b:best.lab.b,r:best.r,g:best.g,bb:best.b})}for(var iter=0;iter<8;iter++){var sums=[];for(i=0;i<centers.length;i++)sums.push({w:0,l:0,a:0,b:0,r:0,g:0,bb:0,n:0});for(i=0;i<samples.length;i++){var bi=0,bd=1e9;for(j=0;j<centers.length;j++){var dd=labDistance(samples[i].lab,centers[j]);if(dd<bd){bd=dd;bi=j}}var sw=samples[i].w,su=sums[bi];su.w+=sw;su.l+=samples[i].lab.l*sw;su.a+=samples[i].lab.a*sw;su.b+=samples[i].lab.b*sw;su.r+=samples[i].r*sw;su.g+=samples[i].g*sw;su.bb+=samples[i].b*sw;su.n++}for(i=0;i<centers.length;i++)if(sums[i].w>0)centers[i]={l:sums[i].l/sums[i].w,a:sums[i].a/sums[i].w,b:sums[i].b/sums[i].w,r:sums[i].r/sums[i].w,g:sums[i].g/sums[i].w,bb:sums[i].bb/sums[i].w,w:sums[i].w,n:sums[i].n}}var total=0;for(i=0;i<centers.length;i++)total+=centers[i].w||0;centers=centers.filter(function(c){return(c.w||0)>Math.max(2,total*.018)&&(c.n||0)>=3});centers.sort(function(a,b){return(b.w||0)-(a.w||0)});var merged=[];for(i=0;i<centers.length;i++){var found=-1;for(j=0;j<merged.length;j++)if(labDistance(centers[i],merged[j])<13){found=j;break}if(found<0)merged.push(centers[i]);else{var aa=merged[found],w1=aa.w,w2=centers[i].w,w=w1+w2;aa.l=(aa.l*w1+centers[i].l*w2)/w;aa.a=(aa.a*w1+centers[i].a*w2)/w;aa.b=(aa.b*w1+centers[i].b*w2)/w;aa.r=(aa.r*w1+centers[i].r*w2)/w;aa.g=(aa.g*w1+centers[i].g*w2)/w;aa.bb=(aa.bb*w1+centers[i].bb*w2)/w;aa.w=w}}return merged.slice(0,6).map(function(c){return{l:c.l,a:c.a,b:c.b,r:c.r,g:c.g,b:c.bb,w:c.w}})}
function nearestCluster(lab,clusters){if(!clusters.length)return-1;var bi=0,bd=1e9;for(var i=0;i<clusters.length;i++){var d=labDistance(lab,clusters[i]);if(d<bd){bd=d;bi=i}}return bi}
function analyze(){if(!source)return;var w=source.width,h=source.height,data=source.data,count=Number(steps.value),slice=w/count,sens=Number(sensitivity.value)/100;paper=estimatePaper();var stride=Math.max(1,Math.floor(Math.min(w,h)/400)),samples=[],sampleCap=8000,seen=0;for(var y=0;y<h;y+=stride){for(var x=0;x<w;x+=stride){var k=(y*w+x)*4,r=data[k],g=data[k+1],b=data[k+2],cl=classifyPixel(r,g,b,sens);if(cl.color){seen++;var weight=cl.hsv.s*(.55+Math.min(1.4,cl.cd/28));var item={r:r,g:g,b:b,lab:cl.lab,w:weight};if(samples.length<sampleCap)samples.push(item);else{var q=Math.floor(random01()*seen);if(q<sampleCap)samples[q]=item}}}}var clusters=buildPalette(samples);updatePalette(clusters);var out=[],notes=0,repeats=0,seals=0;for(var s=0;s<count;s++){var x0=Math.floor(s*slice),x1=Math.min(w,Math.ceil((s+1)*slice)),all=0,ink=0,red=0,weightedY=0,weight=0,clusterWeights=new Float64Array(Math.max(1,clusters.length)),colorCount=0,colorSat=0;for(y=0;y<h;y+=stride){for(x=x0;x<x1;x+=stride){k=(y*w+x)*4;r=data[k];g=data[k+1];b=data[k+2];cl=classifyPixel(r,g,b,sens);all++;if(cl.red)red++;if(cl.color){var ci=nearestCluster(cl.lab,clusters),cw=cl.hsv.s*(.4+Math.min(1.5,cl.cd/24));if(ci>=0)clusterWeights[ci]+=cw;colorCount++;colorSat+=cl.hsv.s}if(cl.ink){var deep=clamp((paper.lab.l-cl.lab.l)/58,.06,1);ink++;weight+=deep;weightedY+=y*deep}}}var inkRatio=ink/Math.max(1,all),redRatio=red/Math.max(1,all),colorRatio=colorCount/Math.max(1,all),has=inkRatio>.003&&weight>0,yPos=has?weightedY/weight:h/2,degree=clamp(Math.round((1-yPos/h)*18),0,18),dominant=-1,domWeight=0;for(var ci2=0;ci2<clusterWeights.length;ci2++)if(clusterWeights[ci2]>domWeight){domWeight=clusterWeights[ci2];dominant=ci2}var colorAccent=dominant>=0&&colorRatio>(.0012+(1-sens)*.0018)&&domWeight>.12,colorDegree=dominant>=0?dominant%7:0,repeat=has&&inkRatio>.043,seal=redRatio>(.0018+(1-sens)*.0014);out.push({degree:degree,has:has,volume:clamp(.38+inkRatio*4.8,.38,.95),repeat:repeat,seal:seal,density:inkRatio,x:s/(count-1||1),color:colorAccent,colorIndex:dominant,colorDegree:colorDegree,colorRatio:colorRatio,colorStrength:clamp(colorRatio*9+(colorSat/Math.max(1,colorCount))*.34,.18,.95)});if(has)notes++;if(repeat)repeats++;if(seal)seals++}events=out;$('nNotes').textContent=notes+'音';$('nRepeat').textContent=repeats+'か所';$('nSeal').textContent=seals+'か所';$('nColor').textContent=clusters.length+'色';analysisLabel.textContent=count+' SLICES / '+clusters.length+' COLORS';generate.disabled=false;var paperHex='#'+toHex(paper.r)+toHex(paper.g)+toHex(paper.b);setStatus('紙色 '+paperHex.toUpperCase()+' を差し引いて、'+clusters.length+'色を検出しました。違う場合は「彩色検出の感度」を調整してください。')}
function makeSong(){if(!events.length){setStatus('先に御朱印の写真を選んでください。');return}generate.disabled=true;listen.disabled=true;setStatus('金属の櫛歯とゼンマイ音を合成しています…');previewCard.classList.add('playing');setTimeout(function(){try{var key=chooseKey(),sr=32000,stepSec=60/Number(bpm.value)/2,intro=1.48,tail=3.4,duration=intro+events.length*stepSec+tail,left=new Float32Array(Math.ceil(duration*sr)),right=new Float32Array(Math.ceil(duration*sr)),mech=Number(mechanism.value)/100,seed=Math.floor(random01()*2147483000),previous=null,sealIndex=0;addWindUp(left,right,sr,mech,seed+7);for(var i=0;i<events.length;i++){var e=events[i],t=intro+i*stepSec+(random01()-.5)*stepSec*.035;if(e.has){var idx=clamp(e.degree,0,key.notes.length-1),midi=key.notes[idx];if(previous!==null&&Math.abs(midi-previous)>10){while(midi-previous>9)midi-=12;while(previous-midi>9)midi+=12}previous=midi;addMusicBox(left,right,sr,t,midi,e.volume,(e.x-.5)*.55,seed+i*31,3.4);if(e.repeat)addMusicBox(left,right,sr,t+stepSec*.42,midi+((i%3===0)?2:0),e.volume*.48,(e.x-.5)*.48,seed+i*31+3,2.4)}if(e.color){var colorMidi=key.base+key.intervals[e.colorDegree%7]+12;while(colorMidi>91)colorMidi-=12;var colorPan=clamp(((e.colorIndex||0)/Math.max(1,paletteClusters.length-1)-.5)*1.2,-.72,.72),colorVol=.16+e.colorStrength*.26;addMusicBox(left,right,sr,t+stepSec*.18,colorMidi,colorVol,colorPan,seed+2200+i*17,2.5);if(e.colorRatio>.024)addMusicBox(left,right,sr,t+stepSec*.55,colorMidi+((e.colorDegree%2)?3:4),colorVol*.52,-colorPan*.55,seed+2300+i*19,1.9)}if(e.seal){var degreeRoot=(sealIndex%2===0)?0:4,root=48+key.pc+key.intervals[degreeRoot%7];while(root>58)root-=12;var triad=key.minor?[0,3,7]:[0,4,7];for(var c=0;c<triad.length;c++)addMusicBox(left,right,sr,t,root+triad[c],.35,-.12+c*.12,seed+900+i*11+c,3.8);sealIndex++}}var cadence=intro+events.length*stepSec+.15,finalRoot=60+key.pc;while(finalRoot<64)finalRoot+=12;while(finalRoot>72)finalRoot-=12;addMusicBox(left,right,sr,cadence,finalRoot,.88,0,seed+4000,3.8);addMusicBox(left,right,sr,cadence,finalRoot+7,.48,.13,seed+4001,3.3);addMechanismBed(left,right,sr,intro,cadence+1.2,stepSec,mech,seed+88);normalize(left,right);$('keyName').textContent=key.jp+' / '+key.name;analysisLabel.textContent=key.name.toUpperCase()+' / '+events.length+' STEPS';useBlob(wavStereo(left,right,sr),'goshuin-musicbox-'+key.name.replace(' ','-')+'.wav',{intro:intro,length:events.length*stepSec+1.3})}catch(err){setStatus('生成エラー：'+err.message)}generate.disabled=false;previewCard.classList.remove('playing')},35)}
function loadImage(selected){if(!selected)return;var lower=(selected.name||'').toLowerCase(),looksImage=!selected.type||selected.type.indexOf('image/')===0||/\.(jpe?g|png|webp|gif|heic|heif)$/i.test(lower);if(!looksImage){setStatus('画像ファイルを選んでください。');return}fileName.textContent=selected.name;setStatus('写真を読み込んでいます…');var url=URL.createObjectURL(selected),img=new Image();img.onload=function(){var ratio=Math.min(1200/img.naturalWidth,1600/img.naturalHeight,1);canvas.width=Math.max(1,Math.round(img.naturalWidth*ratio));canvas.height=Math.max(1,Math.round(img.naturalHeight*ratio));ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);source=ctx.getImageData(0,0,canvas.width,canvas.height);canvas.hidden=false;empty.hidden=true;URL.revokeObjectURL(url);analyze()};img.onerror=function(){URL.revokeObjectURL(url);setStatus('画像を開けませんでした。端末でJPEG・PNG・WebPに変換して試してください。')};img.decoding='async';img.src=url}
function startScan(){cancelAnimationFrame(scanFrame);scan.classList.add('active');previewCard.classList.add('playing');function frame(){if(audio.paused||audio.ended){scan.classList.remove('active');previewCard.classList.remove('playing');return}var intro=songMeta?songMeta.intro:0,length=songMeta?songMeta.length:Math.max(1,audio.duration),p=clamp((audio.currentTime-intro)/Math.max(.1,length),0,1);scan.style.left=(p*100)+'%';scanFrame=requestAnimationFrame(frame)}frame()}
['dragenter','dragover'].forEach(function(type){dropZone.addEventListener(type,function(e){e.preventDefault();e.stopPropagation();dropZone.classList.add('dragover')})});['dragleave','drop'].forEach(function(type){dropZone.addEventListener(type,function(e){e.preventDefault();e.stopPropagation();dropZone.classList.remove('dragover')})});dropZone.addEventListener('drop',function(e){var f=e.dataTransfer&&e.dataTransfer.files&&e.dataTransfer.files[0];if(f)loadImage(f)});dropZone.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();file.click()}});file.addEventListener('change',function(){loadImage(file.files&&file.files[0])});steps.addEventListener('input',function(){$('stepsOut').textContent=steps.value;if(source)analyze()});sensitivity.addEventListener('input',function(){$('sensitivityOut').textContent=sensitivity.value;if(source)analyze()});bpm.addEventListener('input',function(){$('bpmOut').textContent=bpm.value});mechanism.addEventListener('input',function(){$('mechanismOut').textContent=mechanism.value});test.addEventListener('click',makeTest);generate.addEventListener('click',makeSong);listen.addEventListener('click',function(){if(!audio.src){setStatus('先に音声を作ってください。');return}audio.play().then(function(){setStatus('再生中です。');startScan()}).catch(function(){setStatus('下の標準プレーヤーの「▶︎」を押してください。')})});audio.addEventListener('play',startScan);audio.addEventListener('pause',function(){scan.classList.remove('active');previewCard.classList.remove('playing')});audio.addEventListener('ended',function(){scan.classList.remove('active');previewCard.classList.remove('playing');scan.style.left='0%'});window.addEventListener('error',function(e){setStatus('エラー：'+e.message)});
})();
